name: rollbar_flutter_aio
description: Connect your Flutter applications to Rollbar for error reporting.
version: 2.0.0
homepage: https://www.rollbar.com
documentation: https://docs.rollbar.com/docs/flutter#flutter
repository: https://github.com/rollbar/rollbar-flutter

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.7.0
  connectivity_plus: ^4.0.0
  sqlite3_flutter_libs: ^0.5.12
  http: '>=0.13.0 <2.0.0'
  collection: ^1.16.0
  sqlite3: ^1.7.0
  uuid: ^4.1.0
  stack_trace: ^1.10.0

dev_dependencies:
  lints: ^2.0.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  mockito: ^5.3.0
  pubspec_parse: ^1.2.0
  
flutter:
  plugin:
    platforms:
      android:
        package: com.rollbar.flutter
        pluginClass: RollbarFlutterPlugin
      ios:
        pluginClass: RollbarFlutterPlugin
